language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kunone/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kunone/docker-react yarn test --coverage